In [6]:
# import pymysql

# connection = pymysql.connect(
#         host="127.0.0.1",    # DBMS 의 ip(host) : str
#         port=3306,           # DBMS의 port 번호: int
#         user='root',        # username: str
#         password="1111",    # password: str
#         db="test",
#         charset="utf8",
#         cursorclass=pymysql.cursors.DictCursor)
# try:
#     with connection.cursor() as cursor:
#         create_sql = """
#         create table oil_staion (
#         id INT AUTO_INCREMENT PRIMARY KEY,
#         station_name varchar(20),
#         address varchar(40),
#         brand varchar(10),
#         gasolin_price INT,
#         diesel_price INT,
#         self_service BOOLEAN,
#         car_wash BOOLEAN,
#         convenience_store BOLLEAN,
#         24_hour BOOLEAN
#         );
#         """
#         cursor.execute(create_sql)
#         connection.commit()
# finally :
#     connection.close()

In [7]:
import pandas as pd
import pymysql

# CSV 파일 읽기
csv_path = r"C:\Users\Playdata\Documents\SKN13-1st-3Team\crawling\주유소정보.csv"
df = pd.read_csv(csv_path, encoding='utf-8')

df = df.rename(columns={
    '이름': 'station_name',
    '주소': 'address',
    '브랜드': 'brand',
    '지역': 'region',
    '휘발유': 'gasoline_price',
    '경유': 'diesel_price',
    '셀프': 'self_service',
    '세차': 'car_wash',
    '편의점': 'convenience_store',
    '24시간': 'hours_24'
})

    지역                   이름                       주소       브랜드    휘발유     경유  \
0  강남구          (주)보성 세곡주유소     서울 강남구 헌릉로 731 (세곡동)     SK에너지  1,638  1,528
1  강남구             오일프러스 셀프  서울 강남구 남부순환로 2651 (도곡동)     SK에너지  1,679  1,579
2  강남구        지에스칼텍스㈜ 은마주유소          서울 강남구 영동대로 235     GS칼텍스  1,679  1,659
3  강남구  HD현대오일뱅크㈜직영 강남셀프주유소           서울 강남구 도곡로 208  HD현대오일뱅크  1,684  1,604
4  강남구  HD현대오일뱅크㈜직영 도곡셀프주유소        서울 강남구 남부순환로 2718  HD현대오일뱅크  1,684  1,589

  셀프 세차 편의점 24시간
0  Y  Y   N    N
1  Y  Y   N    Y
2  N  Y   N    N
3  Y  Y   N    N
4  Y  Y   N    N

In [12]:
!pip install sqlalchemy pymysql pandas

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: pymysql in c:\users\playdata\miniconda3\lib\site-packages (1.1.1)
Requirement already satisfied: pandas in c:\users\playdata\miniconda3\lib\site-packages (2.2.3)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.1.1-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\playdata\miniconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\playdata\miniconda3\lib\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\playdata\miniconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\playdata\miniconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\playdata\miniconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\playdata\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 40.1 MB/s eta 0:00:00
Downloading greenlet-3.1.1-cp312-cp312-win_amd64.whl (299 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.1.1 sqlalchemy-2.0.40

In [28]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql

# CSV 파일 읽기
csv_path = r"C:\Users\Playdata\Documents\SKN13-1st-3Team\crawling\주유소정보.csv"
df = pd.read_csv(csv_path, encoding='utf-8-sig')

df = df.rename(columns={
    '이름': 'station_name',
    '주소': 'address',
    '지역': 'region',
    '브랜드': 'brand',
    '휘발유': 'gasoline_price',
    '경유': 'diesel_price',
    '셀프': 'self_service',
    '세차': 'car_wash',
    '편의점': 'convenience_store',
    '24시간': 'hours_24'
})

df['gasoline_price'] = df['gasoline_price'].str.replace(',', '').astype(int)
df['diesel_price'] = df['diesel_price'].str.replace(',', '').astype(int)

conn = pymysql.connect(
        host='127.0.0.1', # DB 주소 (예: '127.0.0.1' 또는 AWS RDS 주소)
        port = 3306,
        user='root',    # MySQL 사용자
        password='1111',
        database='gas_station',  # 저장할 데이터베이스명
    )

engine = create_engine("mysql+pymysql://root:1111@127.0.0.1:3306/gas_station")

df.to_sql(name='gas_station', con=engine, if_exists='append', index=False)

print("데이터 저장 완료!")

OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'gasoline_price' in 'field list'")
[SQL: INSERT INTO gas_station (region, station_name, address, brand, gasoline_price, diesel_price, self_service, car_wash, convenience_store, hours_24) VALUES (%(region)s, %(station_name)s, %(address)s, %(brand)s, %(gasoline_price)s, %(diesel_price)s, %(self_service)s, %(car_wash)s, %(convenience_store)s, %(hours_24)s)]
[parameters: [{'region': '강남구', 'station_name': '(주)보성 세곡주유소', 'address': '서울 강남구 헌릉로 731 (세곡동)', 'brand': 'SK에너지', 'gasoline_price': 1638, 'diesel_price': 1528, 'self_service': 'Y', 'car_wash': 'Y', 'convenience_store': 'N', 'hours_24': 'N'}, {'region': '강남구', 'station_name': '오일프러스 셀프', 'address': '서울 강남구 남부순환로 2651 (도곡동)', 'brand': 'SK에너지', 'gasoline_price': 1679, 'diesel_price': 1579, 'self_service': 'Y', 'car_wash': 'Y', 'convenience_store': 'N', 'hours_24': 'Y'}, {'region': '강남구', 'station_name': '지에스칼텍스㈜ 은마주유소', 'address': '서울 강남구 영동대로 235', 'brand': 'GS칼텍스', 'gasoline_price': 1679, 'diesel_price': 1659, 'self_service': 'N', 'car_wash': 'Y', 'convenience_store': 'N', 'hours_24': 'N'}, {'region': '강남구', 'station_name': 'HD현대오일뱅크㈜직영 강남셀프주유소', 'address': '서울 강남구 도곡로 208', 'brand': 'HD현대오일뱅크', 'gasoline_price': 1684, 'diesel_price': 1604, 'self_service': 'Y', 'car_wash': 'Y', 'convenience_store': 'N', 'hours_24': 'N'}, {'region': '강남구', 'station_name': 'HD현대오일뱅크㈜직영 도곡셀프주유소', 'address': '서울 강남구 남부순환로 2718', 'brand': 'HD현대오일뱅크', 'gasoline_price': 1684, 'diesel_price': 1589, 'self_service': 'Y', 'car_wash': 'Y', 'convenience_store': 'N', 'hours_24': 'N'}, {'region': '강남구', 'station_name': 'HD현대오일뱅크㈜직영 유진주유소', 'address': '서울 강남구 논현로 152 (도곡동)', 'brand': 'HD현대오일뱅크', 'gasoline_price': 1694, 'diesel_price': 1599, 'self_service': 'N', 'car_wash': 'Y', 'convenience_store': 'N', 'hours_24': 'N'}, {'region': '강남구', 'station_name': '방죽주유소', 'address': '서울 강남구 밤고개로 215 (율현동)', 'brand': 'GS칼텍스', 'gasoline_price': 1697, 'diesel_price': 1589, 'self_service': 'Y', 'car_wash': 'Y', 'convenience_store': 'N', 'hours_24': 'N'}, {'region': '강남구', 'station_name': '자곡셀프주유소', 'address': '서울 강남구 밤고개로 120 (자곡동)', 'brand': 'SK에너지', 'gasoline_price': 1697, 'diesel_price': 1589, 'self_service': 'Y', 'car_wash': 'Y', 'convenience_store': 'N', 'hours_24': 'N'}  ... displaying 10 of 421 total bound parameter sets ...  {'region': '중랑구', 'station_name': '신일셀프주유소', 'address': '서울 중랑구 상봉로 58 (망우동)', 'brand': 'SK에너지', 'gasoline_price': 1698, 'diesel_price': 1598, 'self_service': 'Y', 'car_wash': 'Y', 'convenience_store': 'N', 'hours_24': 'Y'}, {'region': '중랑구', 'station_name': '용마로주유소', 'address': '서울 중랑구 용마산로 309 (면목동)', 'brand': 'SK에너지', 'gasoline_price': 1698, 'diesel_price': 1598, 'self_service': 'Y', 'car_wash': 'Y', 'convenience_store': 'N', 'hours_24': 'N'}]]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [9]:
import pandas as pd
# from sqlalchemy import create_engine
import pymysql

# CSV 파일 읽기
csv_path = r"C:\Users\Playdata\Documents\SKN13-1st-3Team\crawling\주유소정보.csv"
df = pd.read_csv(csv_path, encoding='utf-8-sig')

df['gasoline_price'] = df['gasoline_price'].str.replace(',', '').astype(int)
df['diesel_price'] = df['diesel_price'].str.replace(',', '').astype(int)

conn = pymysql.connect(
        host='127.0.0.1', # DB 주소 (예: '127.0.0.1' 또는 AWS RDS 주소)
        port = 3306,
        user='root',    # MySQL 사용자
        password='1111',
        database='gas_station',  # 저장할 데이터베이스명
    )

engine = create_engine(
    f"mysql+pymysql://{db_config['user']}:{db_config['password']}@{db_config['host']}:{db_config['port']}/{db_config['database']}?charset=utf8mb4"
)

cursor = conn.cursor()

insert_sql = "insert into gas_station (station_name, address, brand, region, gasolin_price, diesel_price, self_service, car_wash, convenience_store, hours_24) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"

with pymysql.connect(host='127.0.0.1', port = 3306, user='root', password='1111', database='gas_station') as conn:
    with conn.cursor() as cursor :
       result = cursor.execute(insert_sql, ["(주)보성 세곡주유소", "서울 강남구 헌릉로 731 (세곡동)", "SK에너지", "강남구", 1638, 1528, True, True, False, False])
       conn.commit()
        
print("처리 행수:",result)

처리 행수: 1

In [4]:
import pandas as pd
import pymysql

# CSV 파일 읽기
#csv_path = r"C:\Users\Playdata\Documents\SKN13-1st-3Team\crawling\주유소정보.csv"
#df = pd.read_csv(csv_path, encoding='utf-8')

# MySQL 연결 설정

try :
    conn = pymysql.connect(
        host='127.0.0.1', # DB 주소 (예: '127.0.0.1' 또는 AWS RDS 주소)
        port = 3306,
        user='root',    # MySQL 사용자
        password='1111',
        database='gas_station',  # 저장할 데이터베이스명
    )

    cursor = conn.cursor()

    insert_sql = "insert into gas_station (station_name, address, brand, gasolin_price, diesel_price, self_service, car_wash, convenience_store, hours_24) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"

    with pymysql.connect(host='127.0.0.1', port = 3306, user='root', password='1111', database='gas_station') as conn:
        with conn.cursor() as cursor :
            result = cursor.execute(insert_sql, ["(주)보성 세곡주유소", "서울 강남구 헌릉로 731 (세곡동)", "SK에너지", "강남구", 1638, 1528, "Y", "Y", "N", "N"])
            conn.commit()
        
    print("처리 행수:",result)
    
finally:
    if conn:
        cursor.close()

# SQLAlchemy 엔진 생성
# engine = create_engine(
#     f"mysql+pymysql://{db_config['user']}:{db_config['password']}@{db_config['host']}:{db_config['port']}/{db_config['database']}?charset=utf8mb4"
# )


# 데이터베이스에 저장
# for index, row in df.iterrows():
#     cursor.execute("""
#         INSERT INTO gas_station (station_name, address, brand, gasolin_price, diesel_price,  updated_at)
#         VALUES (%s, %s, %s, %s, %s)
#     """, (row['상호'], row['주소'], row['상표'], row['휘발유'], row['수정일자']))

# conn.commit()
#     print(f"성공! {len(df)}개의 주유소 데이터가 저장되었습니다.")

OperationalError: (1136, "Column count doesn't match value count at row 1")

In [21]:
insert_sql = "insert into gas_staion (station_name, address, brand, gasolin_price, diesel_price, self_service, car_wash, convenience_store, hours_24) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"

with pymysql.connect(host='127.0.0.1', port = 3306, user='root', password='1111', database='gas_station') as conn:
    with conn.cursor() as cursor :
        result = cursor.execute(insert_sql, ["(주)보성 세곡주유소", "서울 강남구 헌릉로 731 (세곡동)", "SK에너지", "강남구", 1638, 1528, "Y", "Y", "N", "N"])
        conn.commit()
        
print("처리 행수:",result)

ProgrammingError: (1146, "Table 'gas_station.gas_staion' doesn't exist")